version: "3.3"
services:
  pravega-zookeeper:
    image: zookeeper:3.6.1
#    ports:
#      - "2181:2181"

  pravega-hdfs:
    image: pravega/hdfs:2.7.7
#    ports:
#      - "2222:2222"
#      - "8020:8020"
#      - "50090:50090"
#      - "50010:50010"
#      - "50020:50020"
#      - "50075:50075"
#      - "50070:50070"
    environment:
      SSH_PORT: 2222
      HDFS_HOST: pravega-hdfs

  pravega-bookie1:
    image: pravega/bookkeeper:0.8.1
#    ports:
#      - "3181:3181"
    restart: always
    environment:
      ZK_URL: pravega-zookeeper:2181
      bookiePort: 3181
    links:
      - pravega-zookeeper

  pravega-bookie2:
      image: pravega/bookkeeper:0.8.1
#      ports:
#        - "3182:3182"
      restart: always
      environment:
        ZK_URL: pravega-zookeeper:2181
        bookiePort: 3182
      links:
        - pravega-zookeeper

  pravega-bookie3:
      image: pravega/bookkeeper:0.8.1
#      ports:
#        - "3183:3183"
      restart: always
      environment:
        ZK_URL: pravega-zookeeper:2181
        bookiePort: 3183
      links:
        - pravega-zookeeper

  pravega-controller:
    image: pravega/pravega:0.8.1
    ports:
      - "9090:9090"
#      - "10080:10080"
    command: controller
    environment:
      WAIT_FOR: pravega-zookeeper:2181
      ZK_URL: pravega-zookeeper:2181
      REST_SERVER_PORT: 10080
      JAVA_OPTS: |
        -Dcontroller.service.rpc.listener.port=9090
        -Xmx1024m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
      SERVICE_HOST_IP: pravega-segmentstore
    links:
      - pravega-zookeeper
      - pravega-segmentstore

  pravega-segmentstore:
    image: pravega/pravega:0.8.1
    ports:
      - "12345:12345"
    command: segmentstore
    environment:
      WAIT_FOR: pravega-bookie1:3181,pravega-bookie2:3182,pravega-bookie3:3183,pravega-hdfs:8020
      TIER2_STORAGE: "HDFS"
      HDFS_REPLICATION: 1
      HDFS_URL: pravega-hdfs:8020
      ZK_URL: pravega-zookeeper:2181
      CONTROLLER_URL: tcp://pravega-controller:9090
      JAVA_OPTS: |
        -Dpravegaservice.service.published.host.nameOrIp=${HOST_IP}
        -Dbookkeeper.ensemble.size=2
        -Dbookkeeper.ack.quorum.size=2
        -Dbookkeeper.write.quorum.size=2
        -Xmx2048m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
    links:
      - pravega-zookeeper
      - pravega-hdfs
      - pravega-bookie1
      - pravega-bookie2
      - pravega-bookie3


 
  flink-jobmanager:
    image: flink:1.10.1-scala_2.12
    restart: always
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar

    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager        

  flink-taskmanager:
    image: flink:1.10.1-scala_2.12
    restart: always
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    deploy:
      replicas: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.memory.process.size: 8192mb
        #taskmanager.memory.flink.size: 

  pravega-nma-ingestor:
    image: java:8
    restart: always
    depends_on:
      - pravega-controller 
    command: java -cp /stream-ingest-0.1.0.jar it.consulthink.oe.ingest.NMAJSONInfiniteWriter --limit 1000 --input-stream nma-input --scope nma --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-ingest/build/libs/stream-ingest-0.1.0.jar:/stream-ingest-0.1.0.jar
    #scale: 1

  flink-nma-duplicator:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 1 -c it.consulthink.oe.flink.packetcount.NMADuplicator /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager


  flink-nma-datacontrol-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.AnomalyControlReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream nma-input-datacontrol --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-anomalycontrol-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.AnomalyControlReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream nma-input-anomaly --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-total-traffic-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.TotalTrafficReader /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input-total-traffic --output-stream total-traffic --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-total-traffic-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.TotalTrafficReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --parallelism 2 --input-stream total-traffic --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-anomaly-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.moa.AnomalyReader /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input-anomaly --output-stream anomaly --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-anomaly-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.AnomalyReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream anomaly --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-traffic-by-direction-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.TrafficByDirection /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input-traffic-by-direction --output-stream traffic-by-direction --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-traffic-by-direction-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.TrafficByDirectionToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream traffic-by-direction --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-synin-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.SynInCount /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input-synin --output-stream synin --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-synin-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.SyninReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream synin --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-sessions-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.SessionReader /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input-sessions --output-stream sessions --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-sessions-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.SessionReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream sessions --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-distinctips-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.DistinctIPReader2 /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input-distinctips --output-stream distinctips --controller tcp://pravega-controller:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink--nma-distinctips-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega-controller 
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 4 -c it.consulthink.oe.readers.DistinctIpToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream distinctips --controller tcp://pravega-controller:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager



  influxdb1:
    image: docker.io/influxdb:1.7
    ports:
      - 8083:8083
      - 8086:8086
    #volumes:
    #  - ./data:/var/lib/influxdb
    restart: always
    environment:
      INFLUXDB_DB: nma
      INFLUXDB_HOST: influxdb1
      INFLUXDB_PASSWORD: password
      INFLUXDB_USERNAME: admin

  influxdb2:
    image: docker.io/influxdb:2.0
    ports:
      #- 8183:8083
      - 8186:8086
    #volumes:
    #  - ./data:/var/lib/influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: it.consulthink
      DOCKER_INFLUXDB_INIT_BUCKET: nma
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: D1ARPWX51_G5fP93DI9TYB13cvP_E0qN4yzFDktafhpzXul2-ItLLqKben2qyzMnjkibyAd-ag4A14Iifrq95A==


  grafana:
    image: docker.io/grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./grafana/config/grafana-dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
      - ./grafana/config/influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb-datasource.yaml
      - ./grafana/config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json      
    links:
      - influxdb1
      - influxdb2
    depends_on:
      - influxdb1
      - influxdb2
