version: "3.3"
services:

  pravega:
    image: pravega/pravega:0.8.1
    ports:
      - "12345:12345"
      - "9090:9090"
    command: standalone
    environment:
      JAVA_OPTS: |
        -Dpravegaservice.service.published.host.nameOrIp=${HOST_IP}
        -Xmx4096m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError

  influxdb1:
    image: docker.io/influxdb:1.7
    ports:
      - 8083:8083
      - 8086:8086
    #volumes:
    #  - ./data:/var/lib/influxdb
    restart: always
    environment:
      INFLUXDB_DB: nma
      INFLUXDB_HOST: influxdb1
      INFLUXDB_PASSWORD: password
      INFLUXDB_USERNAME: admin

  grafana:
    image: docker.io/grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./grafana/config/grafana-dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
      - ./grafana/config/influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb-datasource.yaml
      - ./grafana/config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json      
    links:
      - influxdb1
    depends_on:
      - influxdb1