version: "3.3"
services:

  pravega:
    image: pravega/pravega:0.8.1
    restart: always
    #ports:
     # - "12345:12345"
     # - "9090:9090"
    command: standalone
    environment:
      JAVA_OPTS: |
        -Dpravegaservice.service.published.host.nameOrIp=pravega
        -Xmx2048m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError

  influxdb1:
    image: docker.io/influxdb:1.7
    #ports:
      #- 8083:8083
      #- 8086:8086
    #volumes:
    #  - ./data:/var/lib/influxdb
    restart: always
    environment:
      INFLUXDB_DB: nma
      INFLUXDB_HOST: influxdb1
      INFLUXDB_PASSWORD: password
      INFLUXDB_USERNAME: admin

  grafana:
    image: docker.io/grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./grafana/config/grafana-dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
      - ./grafana/config/influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb-datasource.yaml
      - ./grafana/config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json      
    links:
      - influxdb1
    depends_on:
      - influxdb1

  flink-jobmanager:
    image: flink:1.10.1-scala_2.12
    restart: always
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar

    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager        

  flink-taskmanager:
    image: flink:1.10.1-scala_2.12
    restart: always
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    deploy:
      replicas: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.memory.process.size: 8192mb
        #taskmanager.memory.flink.size: 

  pravega-nma-ingestor:
    image: java:8
    restart: always
    depends_on:
      - pravega
    command: java -cp /stream-ingest-0.1.0.jar it.consulthink.oe.ingest.NMAJSONInfiniteWriter --limit 1000 --input-stream nma-input --scope nma --controller tcp://pravega:9090 
    volumes:
      - ../stream-ingest/build/libs/stream-ingest-0.1.0.jar:/stream-ingest-0.1.0.jar
    #scale: 1


  flink-nma-datacontrol-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.AnomalyControlReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream nma-input --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-anomalycontrol-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.AnomalyControlReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream nma-input-anomaly --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-total-traffic-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.TotalTrafficReader /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --output-stream total-traffic --controller tcp://pravega:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-total-traffic-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.TotalTrafficReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --parallelism 2 --input-stream total-traffic --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-anomaly-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.moa.AnomalyReader /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --output-stream anomaly --controller tcp://pravega:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-anomaly-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.AnomalyReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream anomaly --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-traffic-by-direction-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.TrafficByDirection /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --output-stream traffic-by-direction --controller tcp://pravega:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-traffic-by-direction-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.TrafficByDirectionToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream traffic-by-direction --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-synin-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.SynInCount /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --output-stream synin --controller tcp://pravega:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-synin-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.SyninReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream synin --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-sessions-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.SessionReader /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --output-stream sessions --controller tcp://pravega:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-sessions-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.SessionReaderToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream sessions --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-nma-distinctips-processor:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.flink.packetcount.DistinctIPReader2 /opt/flink/usrlib/stream-to-stream-0.1.0.jar --scope nma --input-stream nma-input --output-stream distinctips --controller tcp://pravega:9090 
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink--nma-distinctips-to-influx:
    image: flink:1.10.1-scala_2.12
    restart: "no"
    depends_on:
      - flink-jobmanager
      - influxdb1
      - pravega
    command: /opt/flink/bin/flink run -d --jobmanager flink-jobmanager:8081  --parallelism 2 -c it.consulthink.oe.readers.DistinctIpToInflux /opt/flink/usrlib/various-readers-0.1.0.jar --scope nma --input-stream distinctips --controller tcp://pravega:9090 --influxdbUrl http://influxdb1:8086 --influxdbVersion 1 --influxdbUsername admin --influxdbPassword password --influxdbDb nma
    volumes:
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager


