version: "3.3"
services:
  zookeeper:
    image: zookeeper:3.6.1
#    ports:
#      - "2181:2181"

  hdfs:
    image: pravega/hdfs:2.7.7
#    ports:
#      - "2222:2222"
#      - "8020:8020"
#      - "50090:50090"
#      - "50010:50010"
#      - "50020:50020"
#      - "50075:50075"
#      - "50070:50070"
    environment:
      SSH_PORT: 2222
      HDFS_HOST: hdfs

  bookie1:
    image: pravega/bookkeeper:0.8.1
#    ports:
#      - "3181:3181"
    restart: always
    environment:
      ZK_URL: zookeeper:2181
      bookiePort: 3181
    links:
      - zookeeper

  bookie2:
      image: pravega/bookkeeper:0.8.1
#      ports:
#        - "3182:3182"
      restart: always
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3182
      links:
        - zookeeper

  bookie3:
      image: pravega/bookkeeper:0.8.1
#      ports:
#        - "3183:3183"
      restart: always
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3183
      links:
        - zookeeper

  controller:
    image: pravega/pravega:0.8.1
    ports:
      - "9090:9090"
#      - "10080:10080"
    command: controller
    environment:
      WAIT_FOR: zookeeper:2181
      ZK_URL: zookeeper:2181
      REST_SERVER_PORT: 10080
      JAVA_OPTS: |
        -Dcontroller.service.rpc.listener.port=9090
        -Xmx512m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
      SERVICE_HOST_IP: segmentstore
    links:
      - zookeeper
      - segmentstore

  segmentstore:
    image: pravega/pravega:0.8.1
    ports:
      - "12345:12345"
    command: segmentstore
    environment:
      WAIT_FOR: bookie1:3181,bookie2:3182,bookie3:3183,hdfs:8020
      TIER2_STORAGE: "HDFS"
      HDFS_REPLICATION: 1
      HDFS_URL: hdfs:8020
      ZK_URL: zookeeper:2181
      CONTROLLER_URL: tcp://controller:9090
      JAVA_OPTS: |
        -Dpravegaservice.service.published.host.nameOrIp=${HOST_IP}
        -Dbookkeeper.ensemble.size=2
        -Dbookkeeper.ack.quorum.size=2
        -Dbookkeeper.write.quorum.size=2
        -Xmx512m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
    links:
      - zookeeper
      - hdfs
      - bookie1
      - bookie2
      - bookie3


  flink-jobmanager:
    image: flink:1.10.1-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager        

  flink-taskmanager:
    image: flink:1.10.1-scala_2.12
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - ../stream-processing/build/libs/stream-to-stream-0.1.0.jar:/opt/flink/usrlib/stream-to-stream-0.1.0.jar
      - ../stream-readers/build/libs/various-readers-0.1.0.jar:/opt/flink/usrlib/various-readers-0.1.0.jar
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2 


  influxdb1:
    image: docker.io/influxdb:1.7
    ports:
      - 8083:8083
      - 8086:8086
    #volumes:
    #  - ./data:/var/lib/influxdb
    restart: always
    environment:
      INFLUXDB_DB: nma
      INFLUXDB_HOST: influxdb1
      INFLUXDB_PASSWORD: password
      INFLUXDB_USERNAME: admin

  influxdb2:
    image: docker.io/influxdb:2.0
    ports:
      #- 8183:8083
      - 8186:8086
    #volumes:
    #  - ./data:/var/lib/influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: it.consulthink
      DOCKER_INFLUXDB_INIT_BUCKET: nma
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: D1ARPWX51_G5fP93DI9TYB13cvP_E0qN4yzFDktafhpzXul2-ItLLqKben2qyzMnjkibyAd-ag4A14Iifrq95A==


  grafana:
    image: docker.io/grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./grafana/config/grafana-dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
      - ./grafana/config/influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb-datasource.yaml
      - ./grafana/config/dashboard.json:/var/lib/grafana/dashboards/dashboard.json      
    links:
      - influxdb1
      - influxdb2
    depends_on:
      - influxdb1
      - influxdb2
